#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
	/config/www/{uploads,files,images}

# check for .env and copy default if needed
[[ ! -f "/config/www/.env" ]] && \
	cp /var/www/html/.env.example /config/www/.env

# create symlinks
symlinks=( \
/var/www/html/storage/uploads/files \
/var/www/html/storage/uploads/images \
/var/www/html/public/uploads \
/var/www/html/.env \
/var/www/html/storage/logs/laravel.log
)

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/www/"$(basename "$i")" "$i"
done

# Echo init finish for test runs
if [ -n "${TEST_RUN}" ]; then
	echo '[services.d] done.'
fi

# Create API key if needed
if [ ! -f "/config/BOOKSTACK_APP_KEY.txt" ];
	then
	echo "Generating BookStack app key for first run"
	key=$(php /var/www/html/artisan key:generate --show)
	echo $key > /config/BOOKSTACK_APP_KEY.txt
	echo "App Key set to $key you can modify the file to update /config/BOOKSTACK_APP_KEY.txt"
elif [ -f "/config/BOOKSTACK_APP_KEY.txt" ];
	then
	echo "App Key found - setting variable for seds"
	key=$(cat /config/BOOKSTACK_APP_KEY.txt)
fi

# .env file setup
# check for the default app key or if it has been updated
if grep -Fxq "APP_KEY=SomeRandomString" /config/www/.env || \
! grep -Fxq "APP_KEY=${key}" /config/www/.env; then
	sed -i "s#^APP_KEY=.*#APP_KEY=${key}#" /config/www/.env
fi
# check to see if db_user is set, if it is then run seds and if not then leave them
if [ "${DB_USER}" ];
	then
	echo "Running config - db_user set"
	sed -i "s/DB_HOST=localhost/DB_HOST=${DB_HOST}/g" /config/www/.env
	sed -i "s/DB_DATABASE=database_database/DB_DATABASE=${DB_DATABASE}/g" /config/www/.env
	sed -i "s/DB_USERNAME=database_username/DB_USERNAME=${DB_USER}/g" /config/www/.env
	sed -i "s/DB_PASSWORD=database_user_password/DB_PASSWORD=${DB_PASS}/g" /config/www/.env
fi

# set appurl if detected
[ -n "${APP_URL}" ] && sed -r "s,([#\s]*)?APP_URL=.*,APP_URL=${APP_URL},g" -i /config/www/.env

# check for the mysql endpoint for 30 seconds
END=$((SECONDS+30))
while [ ${SECONDS} -lt ${END} ] && [ -n "${DB_HOST+x}" ]; do
	/usr/bin/nc -z ${DB_HOST} 3306 && \
	if [ ! -z "$(/usr/bin/nc -w1 ${DB_HOST} 3306)" ]; then
		[ ! -z "${RUN}" ] && break
		RUN="RAN"
		# we sleep here again due to first run init on DB containers
		[ ! -f /dbwait.lock ] && sleep 5
	else
		sleep 1
	fi
	sleep 1
done

# update database - will set up database if fresh, or, migrate existing
if [ -z "${CI_RUN+x}" ]; then
	php /var/www/html/artisan migrate --force
fi

# set permissions
chown -R abc:abc \
	/config \
	/var/www/

# set lockfile to avoid DB waits for this specific container
touch /dbwait.lock
